name: Publish packages

on:
  push:
    branches:
      - main

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Set NPM registry auth token
        run: npm set //registry.npmjs.org/:_authToken ${{secrets.NPM_PUBLISH_TOKEN}}
      - name: Set Vendure Hub registry auth token
        run: npm set //registry.vendure.io/:_authToken ${{secrets.VENDURE_HUB_NPM_TOKEN}}
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Stash changes that build might have caused by build
        run: git stash
      - name: Publish
        run: yarn lerna publish from-package --yes
