name: Test packages
on: ['pull_request']

jobs:
  lint:
    name: Prettier formatting and linting check
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install root dependencies
        run: yarn
      - name: Is formatted and linted
        run: yarn lint:check
  test:
    name: ${{ matrix.package }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        package:
          [
            'vendure-order-client',
            'vendure-plugin-admin-ui-helpers',
            'vendure-plugin-admin-social-auth',
            'vendure-plugin-anonymized-order',
            'vendure-plugin-coinbase',
            'vendure-plugin-customer-managed-groups',
            'vendure-plugin-dutch-postalcode',
            'vendure-plugin-e-boekhouden',
            'vendure-plugin-facet-suggestions',
            'vendure-plugin-goedgepickt',
            'vendure-plugin-google-cloud-tasks',
            'vendure-plugin-google-storage-assets',
            'vendure-plugin-invoices',
            'vendure-plugin-limit-variant-per-order',
            'vendure-plugin-metrics',
            'vendure-plugin-modify-customer-orders',
            'vendure-plugin-multiserver-db-sessioncache',
            'vendure-plugin-myparcel',
            'vendure-plugin-order-export',
            'vendure-plugin-picqer',
            'vendure-plugin-popularity-scores',
            'vendure-plugin-primary-collection',
            'vendure-plugin-sendcloud',
            'vendure-plugin-shipping-by-weight-and-country',
            'vendure-plugin-stock-monitoring',
            'vendure-plugin-stripe-subscription',
            'vendure-plugin-variant-bulk-update',
            'vendure-plugin-webhook',
          ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies with Yarn workspaces
        run: yarn
      - name: Build
        run: cd packages/${{ matrix.package }} && yarn build
      - name: Test
        # TEST_ADMIN_UI=true enables Admin UI compilation in tests
        run: |
          cd packages/${{ matrix.package }}
          TEST_ADMIN_UI=true yarn test
