name: Test packages
on: ['pull_request']

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Yarn root
        run: yarn
      - name: Prettier
        run: yarn prettier:check
  test:
    name: Build & test ${{ matrix.package }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        package:
          [
            'vendure-plugin-coinbase',
            'vendure-plugin-dutch-postalcode',
            'vendure-plugin-e-boekhouden',
            'vendure-plugin-goedgepickt',
            'vendure-plugin-google-cloud-tasks',
            'vendure-plugin-google-storage-assets',
            'vendure-plugin-invoices',
            'vendure-plugin-myparcel',
            'vendure-plugin-webhook',
          ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Build test-utils
        run: cd packages/test && yarn
      - name: Build utils
        run: cd packages/util && yarn
      - name: Build
        run: cd packages/${{ matrix.package }} && yarn && yarn build
      - name: Test
        run: cd packages/${{ matrix.package }} && yarn test
