name: Test packages
on: ['pull_request']

jobs:
  test:
    name: Run tests for all packages
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn
      - name: Build test-utils
        run: cd packages/test && yarn && yarn build
      - name: Test vendure-plugin-dutch-postalcode
        run: cd packages/vendure-plugin-dutch-postalcode && yarn && yarn build && yarn test
