name: Test packages
on: ['pull_request']

jobs:
  collect_dirs:
    name: Collect package names
    runs-on: ubuntu-latest
    outputs:
      dirs: ${{ steps.dirs.outputs.dirs }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - id: dirs
        # This command will list all directories in the packages directory
        run: echo "dirs=$(ls -d packages/*/ | jq --raw-input --slurp --compact-output 'split("\n")[:-1]')" >> ${GITHUB_OUTPUT}
  test:
    needs: collect_dirs
    name: ${{ matrix.package }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        package: ${{ fromJson(needs.collect_dirs.outputs.dirs) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '22'
      - name: Install dependencies with Yarn workspaces
        run: yarn
      - name: Build
        run: cd ${{ matrix.package }} && yarn build
      - name: Lint
        run: cd ${{ matrix.package }} && yarn lint
      - name: Test
        run: |
          cd ${{ matrix.package }}
          TEST_ADMIN_UI=true yarn test
