name: Test packages
on: ['pull_request']

jobs:
  test:
    name: Run tests for all packages
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn
      - name: Prettier
        run: yarn prettier:check
      - name: Build test-utils
        run: cd packages/test && yarn
      - name: Build utils
        run: cd packages/util && yarn
      - name: vendure-plugin-dutch-postalcode
        if: always()
        run: cd packages/vendure-plugin-dutch-postalcode && yarn && yarn build && yarn test
      - name: vendure-plugin-google-cloud-tasks
        if: always()
        run: cd packages/vendure-plugin-google-cloud-tasks && yarn && yarn build && yarn test
      - name: vendure-plugin-google-storage-assets
        if: always()
        run: cd packages/vendure-plugin-google-storage-assets && yarn && yarn build && yarn test
      - name: vendure-plugin-myparcel
        if: always()
        run: cd packages/vendure-plugin-myparcel && yarn && yarn build && yarn test
      - name: vendure-plugin-webhook
        if: always()
        run: cd packages/vendure-plugin-webhook && yarn && yarn build && yarn test
      - name: vendure-plugin-goedgepickt
        if: always()
        run: cd packages/vendure-plugin-goedgepickt && yarn && yarn build && yarn test
      - name: vendure-plugin-invoice
        if: always()
        run: cd packages/vendure-plugin-invoices && yarn && yarn build && yarn test
      - name: vendure-plugin-coinbase
        if: always()
        run: cd packages/vendure-plugin-coinbase && yarn && yarn build && yarn test
      - name: vendure-plugin-e-boekhouden
        if: always()
        run: cd packages/vendure-plugin-e-boekhouden && yarn && yarn build && yarn test
